groups:
  admin:
    users: [ciadmin1]

  common-user:
    users: [ciuser1]

permissions:
  admin:
    groups: [admin, common-user]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /*
