default_group: everybody

users:
  admin:
    email: admin@spiffworkflow.org
    password: admin
    preferred_username: Admin

groups:
  admin:
    users:
      [
        admin,
        jakub,
        kb,
        alex,
        dan,
        mike,
        jason@sartography.com,
        jarrad,
        elizabeth,
        jon,
      ]

  Finance Team:
    users:
      [
        jakub,
        alex,
        dan,
        mike,
        jason@sartography.com,
        amir,
        jarrad,
        elizabeth,
        jon,
        sasha,
        fin,
        fin1,
      ]

  demo:
    users:
      [
        core,
        fin,
        fin1,
        harmeet,
        jason@sartography.com,
        sasha,
        manuchehr,
        lead,
        lead1
      ]

  core-contributor:
    users:
      [
        core,
        harmeet,
      ]
  admin-ro:
    users:
      [
        j,
      ]

  test:
    users: [natalia]

permissions:
  admin:
    groups: [admin]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /*
  admin-readonly:
    groups: [admin-ro]
    users: []
    allowed_permissions: [read]
    uri: /*
  admin-process-instances-for-readonly:
    groups: [admin-ro]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-instances/*

  tasks-crud:
    groups: [everybody]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/tasks/*
  service-tasks:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/service-tasks
  user-groups-for-current-user:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/user-groups/for-current-user

  # read all for everybody
  read-all-process-groups:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-groups/*
  read-all-process-models:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-models/*
  read-all-process-instances-for-me:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-instances/for-me/*
  read-process-instance-reports:
    groups: [everybody]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-instances/reports/*
  processes-read:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/processes


  manage-procurement-admin:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-groups/manage-procurement:*
  manage-procurement-admin-slash:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-groups/manage-procurement/*
  manage-procurement-admin-models:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-models/manage-procurement:*
  manage-procurement-admin-models-slash:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-models/manage-procurement/*
  manage-procurement-admin-instances:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-instances/manage-procurement:*
  manage-procurement-admin-instances-slash:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-instances/manage-procurement/*

  finance-admin:
    groups: ["Finance Team"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-groups/manage-procurement:procurement:*

  manage-revenue-streams-instances:
    groups: ["core-contributor", "demo"]
    users: []
    allowed_permissions: [create, read]
    uri: /v1.0/process-instances/manage-revenue-streams:product-revenue-streams:customer-contracts-trade-terms/*

  manage-procurement-invoice-instances:
    groups: ["core-contributor", "demo"]
    users: []
    allowed_permissions: [create, read]
    uri: /v1.0/process-instances/manage-procurement:procurement:core-contributor-invoice-management:*

  manage-procurement-instances:
    groups: ["core-contributor", "demo"]
    users: []
    allowed_permissions: [create, read]
    uri: /v1.0/process-instances/manage-procurement:vendor-lifecycle-management:*

  create-test-instances:
    groups: ["test"]
    users: []
    allowed_permissions: [create, read]
    uri: /v1.0/process-instances/misc:test:*

  core1-admin-instances:
    groups: ["core-contributor", "Finance Team"]
    users: []
    allowed_permissions: [create, read]
    uri: /v1.0/process-instances/misc:category_number_one:process-model-with-form:*
  core1-admin-instances-slash:
    groups: ["core-contributor", "Finance Team"]
    users: []
    allowed_permissions: [create, read]
    uri: /v1.0/process-instances/misc:category_number_one:process-model-with-form/*
