default_group: everybody

groups:
  admin:
    users:
      [
        jakub,
        kb,
        alex,
        dan,
        mike,
        jason,
        amir,
        jarrad,
        elizabeth,
        jon,
        natalia,
        harmeet,
        sasha,
        manuchehr,
      ]

  Finance Team:
    users:
      [
        jakub,
        alex,
        dan,
        mike,
        jason,
        amir,
        jarrad,
        elizabeth,
        jon,
        natalia,
        sasha,
        fin,
      ]

  Project Lead:
    users:
      [
        jakub,
        alex,
        dan,
        mike,
        jason,
        jarrad,
        elizabeth,
        jon,
        natalia,
        manuchehr,
        lead,
      ]

  core-contributor:
    users: [core]

permissions:
  tasks-crud:
    groups: [everybody]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/tasks/*

  admin:
    groups: [admin]
    users: []
    allowed_permissions: [create, read, update, delete, list, instantiate]
    uri: /*

  read-all:
    groups: ["Finance Team", "Project Lead", admin]
    users: []
    allowed_permissions: [read]
    uri: /*

  read-process-group-list:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-groups
  read-process-model-list:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-models

  manage-procurement-admin:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-groups/manage-procurement:*
  manage-procurement-admin-slash:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-groups/manage-procurement/*
  manage-procurement-admin-models:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-models/manage-procurement:*
  manage-procurement-admin-models-slash:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-models/manage-procurement/*
  manage-procurement-admin-instances:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-instances/manage-procurement:*
  manage-procurement-admin-instances-slash:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-instances/manage-procurement/*

  finance-admin:
    groups: ["Finance Team"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-groups/manage-procurement:procurement:vendor-invoice-management:*
  finance-admin-slash:
    groups: ["Finance Team"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-groups/manage-procurement:procurement:vendor-invoice-management/*
  finance-admin-models:
    groups: ["Finance Team"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-models/manage-procurement:procurement:vendor-invoice-management:*
  finance-admin-models-slash:
    groups: ["Finance Team"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-models/manage-procurement:procurement:vendor-invoice-management/*
  finance-admin-instances:
    groups: ["Finance Team"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-instances/manage-procurement:procurement:vendor-invoice-management:*
  finance-admin-instances-slash:
    groups: ["Finance Team"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-instances/manage-procurement:procurement:vendor-invoice-management/*

  core-admin:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-groups/manage-procurement:procurement:vendor-invoice-management:*
  core-admin-slash:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-groups/manage-procurement:procurement:vendor-invoice-management/*
  core-admin-models:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-models/manage-procurement:procurement:vendor-invoice-management:*
  core-admin-models-slash:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-models/manage-procurement:procurement:vendor-invoice-management/*
  core-admin-models-instantiate:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [create]
    uri: /v1.0/process-models/manage-procurement:procurement:vendor-invoice-management:invoice-approval/process-instances
  core-admin-instances:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [create, read]
    uri: /v1.0/process-instances/manage-procurement:procurement:vendor-invoice-management:*
  core-admin-instances-slash:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [create, read]
    uri: /v1.0/process-instances/manage-procurement:procurement:vendor-invoice-management/*

  core1-admin:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-groups/misc:category_number_one:*
  core1-admin-slash:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-groups/misc:category_number_one/*
  core1-admin-models:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-models/misc:category_number_one:process-model-with-form:*
  core1-admin-models-slash:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-models/misc:category_number_one:process-model-with-form/*
  core1-admin-models-instantiate:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [create]
    uri: /v1.0/process-models/misc:category_number_one:process-model-with-form/process-instances
  core1-admin-instances:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [create, read]
    uri: /v1.0/process-instances/misc:category_number_one:process-model-with-form:*
  core1-admin-instances-slash:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [create, read]
    uri: /v1.0/process-instances/misc:category_number_one:process-model-with-form/*
