default_group: everybody

groups:
  admin:
    users:
      [
        admin,
        jakub,
        kb,
        alex,
        dan,
        mike,
        jason,
        j,
        jarrad,
        elizabeth,
        jon,
        natalia,
      ]

  Finance Team:
    users:
      [
        jakub,
        alex,
        dan,
        mike,
        jason,
        j,
        amir,
        jarrad,
        elizabeth,
        jon,
        natalia,
        sasha,
        fin,
        fin1,
      ]

  demo:
    users:
      [
        core,
        fin,
        fin1,
        harmeet,
        sasha,
        manuchehr,
        lead,
        lead1
      ]

  core-contributor:
    users:
      [
        core,
        harmeet,
      ]

permissions:
  admin:
    groups: [admin]
    users: []
    allowed_permissions: [read]
    uri: /*
  admin-process-instances:
    groups: [admin]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /process-instances/*

  tasks-crud:
    groups: [everybody]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /tasks/*

  service-tasks:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /service-tasks
  user-groups-for-current-user:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /user-groups/for-current-user


  # read all for everybody
  read-all-process-groups:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /process-groups/*
  read-all-process-models:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /process-models/*
  read-all-process-instances-for-me:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /process-instances/for-me/*
  manage-process-instance-reports:
    groups: [everybody]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /process-instances/reports/*
  processes-read:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /processes


  manage-procurement-admin-instances:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /process-instances/manage-procurement:*
  manage-procurement-admin-instances-slash:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /process-instances/manage-procurement/*
  manage-procurement-admin-instance-logs:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [read]
    uri: /logs/manage-procurement:*
  manage-procurement-admin-instance-logs-slash:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [read]
    uri: /logs/manage-procurement/*

  manage-revenue-streams-instances:
    groups: ["core-contributor", "demo"]
    users: []
    allowed_permissions: [create, read]
    uri: /process-instances/manage-revenue-streams:product-revenue-streams:customer-contracts-trade-terms/*
  manage-revenue-streams-instance-logs:
    groups: ["core-contributor", "demo"]
    users: []
    allowed_permissions: [read]
    uri: /logs/manage-revenue-streams:product-revenue-streams:customer-contracts-trade-terms/*

  manage-procurement-invoice-instances:
    groups: ["core-contributor", "demo"]
    users: []
    allowed_permissions: [create, read]
    uri: /process-instances/manage-procurement:procurement:core-contributor-invoice-management:*
  manage-procurement-invoice-instance-logs:
    groups: ["core-contributor", "demo"]
    users: []
    allowed_permissions: [read]
    uri: /logs/manage-procurement:procurement:core-contributor-invoice-management:*

  manage-procurement-instances:
    groups: ["core-contributor", "demo"]
    users: []
    allowed_permissions: [create, read]
    uri: /process-instances/manage-procurement:vendor-lifecycle-management:*
  manage-procurement-instance-logs:
    groups: ["core-contributor", "demo"]
    users: []
    allowed_permissions: [read]
    uri: /logs/manage-procurement:vendor-lifecycle-management:*
