default_group: everybody

groups:
  admin:
    users:
      [
        admin,
        jakub,
        kb,
        alex,
        dan,
        mike,
        jason,
        j,
        amir,
        jarrad,
        elizabeth,
        jon,
        natalia,
      ]

  Finance Team:
    users:
      [
        jakub,
        alex,
        dan,
        mike,
        jason,
        j,
        amir,
        jarrad,
        elizabeth,
        jon,
        natalia,
        sasha,
        fin,
        fin1,
      ]

  demo:
    users:
      [
        core,
        fin,
        fin1,
        harmeet,
        sasha,
        manuchehr,
        lead,
        lead1
      ]

  core-contributor:
    users:
      [
        core,
        harmeet,
      ]

permissions:
  admin:
    groups: [admin]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /*

  tasks-crud:
    groups: [everybody]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/tasks/*

  # read all for everybody
  read-all-process-groups:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-groups/*
  read-all-process-models:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-models/*
  read-all-process-instance:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-instances/*
  read-process-instance-reports:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/process-instances/reports/*
  processes-read:
    groups: [everybody]
    users: []
    allowed_permissions: [read]
    uri: /v1.0/processes


  manage-procurement-admin:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-groups/manage-procurement:*
  manage-procurement-admin-slash:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-groups/manage-procurement/*
  manage-procurement-admin-models:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-models/manage-procurement:*
  manage-procurement-admin-models-slash:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-models/manage-procurement/*
  manage-procurement-admin-instances:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-instances/manage-procurement:*
  manage-procurement-admin-instances-slash:
    groups: ["Project Lead"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-instances/manage-procurement/*

  finance-admin:
    groups: ["Finance Team"]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-groups/manage-procurement:procurement:*

  demo-models-instantiate-vendor-block:
    groups: ["demo"]
    users: []
    allowed_permissions: [create]
    uri: /v1.0/process-models/manage-procurement:vendor-lifecycle-management:vendor-md-maintenance:vendor-md-block/process-instances
  demo-models-instantiate-vendor-change:
    groups: ["demo"]
    users: []
    allowed_permissions: [create]
    uri: /v1.0/process-models/manage-procurement:vendor-lifecycle-management:vendor-md-maintenance:vendor-md-change/process-instances
  demo-models-instantiate-vendor-creation:
    groups: ["demo"]
    users: []
    allowed_permissions: [create]
    uri: /v1.0/process-models/manage-procurement:vendor-lifecycle-management:vendor-md-maintenance:vendor-md-creation/process-instances
  demo-models-instantiate-vendor-core-invoice_appoval:
    groups: ["demo"]
    users: []
    allowed_permissions: [create]
    uri: /v1.0/process-models/manage-procurement:procurement:core-contributor-invoice-management:cc-invoice-approval/process-instances
  demo-models-customer-contracts:
    groups: ["demo"]
    users: []
    allowed_permissions: [create]
    uri: /v1.0/process-models/manage-revenue-streams:product-revenue-streams:customer-contracts-trade-terms/process-instances

  core-admin-models-instantiate:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [create]
    uri: /v1.0/process-models/manage-procurement:procurement:core-contributor-invoice-management:cc-invoice-approval/process-instances
  core-admin-instances:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [create, read]
    uri: /v1.0/process-instances/manage-procurement:procurement:core-contributor-invoice-management:*
  core-admin-instances-slash:
    groups: ["core-contributor"]
    users: []
    allowed_permissions: [create, read]
    uri: /v1.0/process-instances/manage-procurement:procurement:core-contributor-invoice-management/*
