default_group: everybody

users:
  testadmin1:
    service: https://testing/openid/thing
    email: testadmin1@spiffworkflow.org
    password: admin
    preferred_username: El administrador de la muerte

groups:
  admin:
    users: [testadmin1, testadmin2]

  Finance Team:
    users: [testuser1, testuser2]

  hr:
    users: [testuser2, testuser3, testuser4]

permissions:
  admin:
    groups: [admin]
    users: []
    allowed_permissions: [create, read, update, delete, list, instantiate]
    uri: /*

  read-all:
    groups: ["Finance Team", hr, admin]
    users: []
    allowed_permissions: [read]
    uri: /*

  tasks-crud:
    groups: [everybody]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /tasks/*

  # TODO: all uris should really have the same structure
  finance-admin-group:
    groups: ["Finance Team"]
    users: [testuser4]
    allowed_permissions: [create, read, update, delete]
    uri: /process-groups/finance/*

  finance-admin-model:
    groups: ["Finance Team"]
    users: [testuser4]
    allowed_permissions: [create, read, update, delete]
    uri: /process-models/finance/*

  finance-admin-model-lanes:
    groups: ["Finance Team"]
    users: [testuser4]
    allowed_permissions: [create, read, update, delete]
    uri: /process-models/finance:model_with_lanes/*

  finance-admin-instance-run:
    groups: ["Finance Team"]
    users: [testuser4]
    allowed_permissions: [create, read, update, delete]
    uri: /process-instances/*
